### ISSUE TITLE
Swarm deploy not working with :latest image tag

### ISSUE THREAD

**Issue by hrodic** [aerospike/aerospike-docker-swarm#4]
latest tag not working.

Fix: replace the tag "latest" with "4.6.0.5"

```
aerospikedb:
        image: aerospike/aerospike-server:4.6.0.5
```

Or upgrade the configuration stack to match the requirements.

**Comment by spkesan** [comment]
Hello @hrodic 

The latest tag will be server version 4.7.0.2. 
https://hub.docker.com/layers/aerospike/aerospike-server/latest/images/sha256-838328ccb4e5753bd550dd8bc205f2b133269f6bc031f63be0800b65f1151771

To use a specific version, the tag should be that version, like 4.6.0.5. 

The `latest` tag works,
```
$ docker run -i -d -t  --name aerospike1 aerospike/aerospike-server:latest
Unable to find image 'aerospike/aerospike-server:latest' locally
latest: Pulling from aerospike/aerospike-server
9fc222b64b0a: Already exists 
7c38d5ee09df: Pull complete 
12cc97469683: Pull complete 
c08a597430db: Pull complete 
Digest: sha256:838328ccb4e5753bd550dd8bc205f2b133269f6bc031f63be0800b65f1151771
Status: Downloaded newer image for aerospike/aerospike-server:latest
40f520db4e7adad45e8d6e77081e2f1b1e49699664c4133390a45affbd225199
```
```
$ docker logs aerospike1
link eth0 state up
link eth0 state up in 0
Oct 17 2019 09:42:20 GMT: INFO (as): (as.c:316) <><><><><><><><><><>  Aerospike Community Edition build 4.7.0.2  <><><><><><><><><><>
Oct 17 2019 09:42:20 GMT: INFO (config): (cfg.c:4110) # Aerospike database configuration file.
Oct 17 2019 09:42:20 GMT: INFO (config): (cfg.c:4110) 
Oct 17 2019 09:42:20 GMT: INFO (config): (cfg.c:4110)
```
Can you confirm it again.

**Comment by hrodic** [comment]
Maybe is related with my VirtualBox swarm environment, but when i use latest swarm aerospikedb replicas fail to startup.

> 
> aerospike_aerospikedb.1.x0diqt2p1d2z@aerospike1    | link eth0 state up
> aerospike_aerospikedb.1.x0diqt2p1d2z@aerospike1    | link eth0 state up in 0
> aerospike_aerospikedb.1.x0diqt2p1d2z@aerospike1    | Oct 17 2019 14:26:16 GMT: FAILED ASSERTION (config): (cfg.c:1687) line 10 :: 'transaction-queues' is obsolete - please configure 'service-threads' carefully
> aerospike_aerospikedb.1.x0diqt2p1d2z@aerospike1    | Oct 17 2019 14:26:16 GMT: WARNING (as): (signal.c:161) SIGINT received, shutting down Aerospike Community Edition build 4.7.0.2 os debian9
> aerospike_aerospikedb.1.x0diqt2p1d2z@aerospike1    | Oct 17 2019 14:26:16 GMT: WARNING (as): (signal.c:164) startup was not complete, exiting immediately

When i go to 4.6 version all works.
```

ID                  NAME                    MODE                REPLICAS            IMAGE                                PORTS
4nw2ztzzlg8x        aerospike_aerospikedb   replicated          3/3                 aerospike/aerospike-server:4.6.0.5   
i2wdcei8pfkm        aerospike_meshworker    replicated          1/1                 aerospike/aerospike-tools:latest 

```

**Comment by spkesan** [comment]
Hello @hrodic 

Are you using your own `aerospike.conf` file? That's okay. You just need to remove
`transaction-queues` and `transaction-threads-per-queue` configuration from your `aerospike.conf` file. These config items have been removed in 4.7.0.2+

**Comment by hrodic** [comment]
Ok, it worked.
FYI, those two params are included by default in master, so might be interesting that you tag this project too to ensure it works out of the box
